#cloud:
#  aws:
#    stack:
#      auto: false
#    region:
#      auto: false
#      static: eu-central-1

spring:
  redis:
    host: localhost
    port: 6379

decorator:
  datasource:
    p6spy:
      enable-logging: true
