server:
  port : 8080

spring:
  messages:
    basename: messages, errors
  profiles:
    active: dev #기본 활성 프로필
  config:
    import: application-oauth.yml

  jpa:
    show_sql: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enable: false # 인메모리로 실행할경우 false로 설정해야 update시 에러 안남

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb
      username: sa
      password:

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error


