server:
  port : 9000

spring:
  messages:
    basename: messages, errors
  profiles:
    active: dev #기본 활성 프로필
  config:
    import: application-oauth.yml

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enable: true

  datasource:
    hikari:
#      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#      jdbc-url: jdbc:p6spy:h2:tcp://localhost/~/test;MODE=LEGACY;
      jdbc-url: jdbc:h2:tcp://localhost/~/test;MODE=LEGACY;
      username: sa
      password:
      driver-class-name: org.h2.Driver

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

decorator:
  datasource:
    p6spy:
      enable-logging: false
