server:
  port : 8080

spring:
  profiles:
    active: dev #기본 활성 프로필
  config:
    import: application-oauth.yml

  jpa:
    show_sql: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enable: true

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb
      username: sa
      password:

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
